### ISSUE TITLE
0.0.1 violates PVP

### ISSUE THREAD

**Issue by phadej** [kazu-yamamoto/http-semantics#7]
```diff
@@@ Network.HTTP.Semantics
 - type InpBody = IO ByteString
 + type InpBody = IO (ByteString, Bool)
```

This is a breaking change.

**Comment by phadej** [comment]
I'd recommend to make 0.0.1 uninstallable. This violation causes https://github.com/kazu-yamamoto/http2/issues/128 (though the affected `http2` versions don't even have any version bounds on `http-semantics`).

**Comment by kazu-yamamoto** [comment]
This is my bad.
Version 0.0.1 has been deprecated.
The current `http2` has a upper boundary for `http-semantics`.
