### ISSUE TITLE
`defaultReadN` should be documented as intended for single-threaded use

### ISSUE THREAD

**Issue by edsko** [kazu-yamamoto/http-semantics#8]
This is a very minor issue, but it might be good to document that [`defaultReadN`](https://github.com/kazu-yamamoto/http-semantics/blob/cbbec7dc3322b17ead9c61a089e00f40e1fc49f3/Network/HTTP/Semantics/ReadN.hs#L17) is intended for single-threaded usage only. (In `http2` this is the case because it's only the frame receiving thread that is using it.)

**Comment by kazu-yamamoto** [comment]
Good point.
A PR is welcome!
